### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by jbauers**

### CODE REVIEW

**Comment by jbauers** [comment]
Regarding the failed test: https://github.com/onelogin/onelogin-go-sdk/pull/27 :slightly_smiling_face:

**Comment by dcaponi** [comment]
Please update the go.mod to point to version 1.0.12 of the OneLogin SDK and your tests should pass. Details on your SDK PR 😄

**Comment by dcaponi** [comment]
LGTM Thanks for catching that 🎉

**Comment by jbauers** [comment]
Thanks for fixing this so quickly!

**Comment by dcaponi** [comment]
EZ PZ. I also pushed it out in a new release version v0.1.2 so it shouldn't be annoying anymore.

**Pull request merged**
