### PR TITLE
Adding onelogin_user datasource

### PR DESCRIPTION
**Pull request by ZsoltPath**
Changing the onelogin_users data source to return a list of IDs for a query
Adding onelogin_user data source to return the details of a single user

### CODE REVIEW

**Comment by ZsoltPath** [comment]
Hi @dcaponi,

Since the SDK is updated, I've added the proper user data sources.

There's one issue though, I've added the data source documentation to #48 but it hasn't appeared on the registry docs
https://registry.terraform.io/providers/onelogin/onelogin/latest/docs
I guess it's because there wasn't any data source before and it's missing from the pipeline.

**Comment by dcaponi** [comment]
Hey @ZsoltPath Thanks so much for helping out with the data-sources side of this. TBH I'm not actually much of a Terraform user myself so the help & insight is much appreciated.

For posterity, Im gonna say in writing that this security warning suppression is fine in the context that we are using MD5 for hashing but not for anything secure or sensitive. 

I will ask however why you went with MD5 and not Base64 encoding or something like that, just so I'm aware of why that choice was made.

I checked up on [provider docs publishing](https://www.terraform.io/docs/registry/providers/docs.html#directory-structure) and I think we're just naming the directory incorrectly. We're calling it `datasources` and this documentation implies the directory should be called `data-sources`. Could you rename the directory as part of this PR and as soon as I merge & cut a release of this we'll see if that was it.

**Comment by ZsoltPath** [comment]
Hi @dcaponi,

I've renamed the directory. Hope it helps.

Regarding the md5 hash, I needed something to turn a query structure to a simple string ID for the terraform resource.
MD5 looked like the easiest solution. I'm not really a Go developer. If you have a more proper idea, I'm happy to change.

**Comment by dcaponi** [comment]
@ZsoltPath looks like directory rename did the trick, thanks! Release is available now.

**Pull request merged**
